#!/usr/bin/env bash
#
# Asserts that `out/` is a usable static site, not merely a build that exited 0.
#
# Every check here corresponds to a way this site has actually broken or could
# break invisibly: an export that emitted nothing, a sitemap that lost its URLs,
# a metadata change that silently dropped canonicals. A passing `next build`
# tells you the compiler was happy; it does not tell you the site works.
#
# Run from the repo root, after `npm run build`.

set -euo pipefail

cd "$(dirname "$0")/.."

fail=0

# `::error::` is a GitHub Actions annotation; harmless noise when run locally.
err() {
  echo "::error::$1"
  fail=1
}

MIN_PAGES=50
MIN_SITEMAP_URLS=40

echo "--- structure"
test -d out       || { err "no out/ — did the build run?"; exit 1; }
test -f out/index.html || err "no out/index.html"
test -d out/_next      || err "no out/_next"

# Each of these is generated by a route handler rather than a page, so it is
# exactly the kind of artifact that can stop being emitted without any page
# visibly breaking.
for f in robots.txt sitemap.xml llms.txt search-index.json opengraph-image.png favicon.ico; do
  test -f "out/$f" || err "missing out/$f"
done

echo "--- counts"
# `|| true` throughout: under `set -e`, grep's exit-1-on-no-match would abort
# the script with no explanation instead of reporting the assertion that failed.
pages=$(find out -name '*.html' | wc -l | tr -d ' ')
echo "html pages:   $pages"
[ "$pages" -ge "$MIN_PAGES" ] || err "only $pages pages, expected >= $MIN_PAGES"

urls=$(grep -c '<loc>' out/sitemap.xml || true)
echo "sitemap urls: $urls"
[ "$urls" -ge "$MIN_SITEMAP_URLS" ] || err "only $urls sitemap urls, expected >= $MIN_SITEMAP_URLS"

echo "--- metadata"
# Error pages are exempt: they are not canonical targets and carry no OG image.
# `find -print0 | xargs -0` rather than mapfile, which is bash 4+ and so absent
# on a stock macOS shell.
indexable() {
  find out -name '*.html' ! -name '404.html' ! -name '_not-found.html' -print0
}

missing_tag() {
  indexable | xargs -0 grep -L "$1" || true
}

check_tag() {
  local pattern="$1" label="$2" hits
  hits=$(missing_tag "$pattern")
  if [ -n "$hits" ]; then
    err "pages without $label:"
    echo "$hits" | sed 's/^/  /'
  fi
}

check_tag 'rel="canonical"'      "a canonical link"
check_tag 'property="og:image"'  "og:image"

# The export is served from a custom domain at the root. An absolute /_next
# reference is correct; a reference to localhost or a bare 127.0.0.1 means a dev
# URL leaked into the build.
leaked=$(grep -rl 'localhost:3000' out --include='*.html' --include='*.js' --include='*.json' || true)
if [ -n "$leaked" ]; then
  err "dev URLs leaked into the export:"
  echo "$leaked" | sed 's/^/  /'
fi

echo
if [ "$fail" -ne 0 ]; then
  echo "export verification FAILED"
  exit 1
fi
echo "export verification passed — $pages pages, $urls sitemap urls"
